### ISSUE TITLE
Adding AUC and F1 score to collection of evaluation metrics

### ISSUE THREAD

**Issue by TianyuDu** [gsbDBI/bemb#16]
@rachelyangzhou

**Comment by rachelyangzhou** [comment]
Keshav just directed me to his very helpful code that computes these metrics: https://github.com/gsbDBI/Learning_Tools_Competition/blob/master/src/notebook/simulated_data/evaluation.py

**Comment by TianyuDu** [comment]
Thank you for linking me to this code, I am adding them to the BEMB package.

**Comment by TianyuDu** [comment]
I have added the support for a couple more metrics (see the screenshot below), hope this provides more insights on model tunning.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/22979098/192959454-d99a0808-f645-46a7-9b7e-52e7cab4699d.png">
